### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by pkopac** [richard-lyman/lithcrypt#1]
cannot find package "code.google.com/p/go.crypto/pbkdf2"

**Comment by cihanozhan** [comment]
pbkdf2 source code ; https://github.com/mclarkson/obdi/tree/master/external/code.google.com/p/go.crypto

**Comment by pkopac** [comment]
That's someone's "alpha" project. And the lib is committed there in `external`. I'd avoid including that in production code. Anyway, the problem is this library needs to be updated with a new reference to that library, otherwise it won't work anymore. Eg. I didn't use it in the end.

**Comment by richard-lyman** [comment]
Thanks for pointing out the need to update the dependency. I'll swap it out for the correct path.
